version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./public:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  node:
    image: node:alpine
    ports:
      - 3000:3000
    volumes:
      - ./server:/app
    working_dir: /app
    command: npm run serve